### ISSUE TITLE
Feature enhancement request:  4 decimal places for BKJD display for SC TPFs

### ISSUE THREAD

**Issue by KenMighell** [KeplerGO/k2flix#21]
The current BKJD display in the GIF movie shows only 2 decimal places.  

Two decimal places suffice for Long Cadence Kepler TargetPixelFiles.

Short Cadence Kepler TargetPixelFiles need 4 decimal places for unambiguous identification of the time associated with any given frame.   

Feature enhancement request:  

When k2flix is reading a SC TPF, show 4 decimal places for the BKJD display.

Thanks!

-Ken Mighell

**Comment by barentsen** [comment]
Thanks for noticing this problem @KenMighell !

This should now have been resolved in commit d4cedf61428761041799db9f739f291643a10489.
